"""create_pc_preco_first_table

Revision ID: 12fd82b1b6c2
Revises: c591a263c682
Create Date: 2025-06-23 13:34:42.807873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fd82b1b6c2'
down_revision: Union[str, None] = 'c591a263c682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_anything_sellerid_sku'), table_name='pc_preco')
    op.create_index(op.f('ix_pc_preco_id'), 'pc_preco', ['id'], unique=False)
    op.create_index(op.f('ix_pc_preco_seller_id'), 'pc_preco', ['seller_id'], unique=False)
    op.create_index(op.f('ix_pc_preco_sku'), 'pc_preco', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pc_preco_sku'), table_name='pc_preco')
    op.drop_index(op.f('ix_pc_preco_seller_id'), table_name='pc_preco')
    op.drop_index(op.f('ix_pc_preco_id'), table_name='pc_preco')
    op.create_index(op.f('idx_anything_sellerid_sku'), 'pc_preco', ['seller_id', 'sku'], unique=True)
    # ### end Alembic commands ###
