services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pc-preco
